version: '3'
services:
  serviceregistry:
    image: 'formationcih/serviceregistry:0.0.1'
    ports:
      - '8761:8761'
    container_name: serviceregistry
  configserver:
    image: 'formationcih/configservice:0.0.1'
    ports:
      - '9296:9296'
    container_name: configserver
    environment:
      - EUREKA_SERVER_ADDRESS=http://host.docker.internal:8761/eureka
    depends_on:
      - serviceregistry
    healthcheck:
      test: ["CMD", "curl","-f","http://configserver:9296/actuator/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5
  cloudgateway:
    image: 'formationcih/cloudgateway:0.0.1'
    ports:
      - '9090:9090'
    container_name: cloudgateway
    environment:
      - EUREKA_SERVER_ADDRESS=http://host.docker.internal:8761/eureka
      - CONFIG_SERVER_URL=configserver
    depends_on:
      configserver:
        condition: service_healthy